# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-08 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import slacky.validators


class Migration(migrations.Migration):

    dependencies = [
        ('slacky', '0005_auto_20171007_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=250, validators=[slacky.validators.validate_content]),
        ),
    ]
