# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import slacky.validators


class Migration(migrations.Migration):

    dependencies = [
        ('slacky', '0006_auto_20171008_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[slacky.validators.validate_content]),
        ),
    ]
