# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slacky', '0007_auto_20171008_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slacky.Tweet'),
        ),
    ]
